(function(){
  const dataset=Array.isArray(window.JM_DINODEX_DATA)?window.JM_DINODEX_DATA:[];
  const esc=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const stripHtml=v=>{const d=document.createElement('div');d.innerHTML=v||'';return(d.textContent||d.innerText||'').replace(/\s+/g,' ').trim();};
  const scientific=s=>s?.scientific||s?.name||'';
  const normalizedTaxon=name=>String(name||'').replace(/\b(spp?|cf|aff)\.?(?=\s|$)/gi,'').replace(/\([^)]*\)/g,'').replace(/\s+/g,' ').trim();
  const genus=name=>(normalizedTaxon(name).match(/[A-Za-z]+/)||[''])[0].toLowerCase();

  /* ---------- universal image viewer ---------- */
  const viewer=document.createElement('div');
  viewer.className='universal-image-viewer';viewer.id='universalImageViewer';viewer.setAttribute('aria-hidden','true');
  viewer.innerHTML=`<div class="universal-image-frame" role="dialog" aria-modal="true" aria-label="Full-size image viewer"><div class="universal-image-toolbar"><span class="led green"></span><span class="universal-image-caption" id="universalImageCaption">IMAGE VIEWER</span><button class="universal-image-close" id="universalImageClose" type="button" aria-label="Close image viewer">×</button></div><div class="universal-image-stage" id="universalImageStage"><img id="universalImage" alt=""></div><div class="universal-image-footer"><span>CLICK IMAGE: FIT / ACTUAL SIZE</span><a id="universalImageSource" href="#" target="_blank" rel="noopener" hidden>SOURCE / LICENSE ↗</a></div></div>`;
  document.body.appendChild(viewer);
  const viewerImg=document.getElementById('universalImage'),viewerCaption=document.getElementById('universalImageCaption'),viewerSource=document.getElementById('universalImageSource');
  function openViewer(img){const full=img.dataset.fullSrc||img.currentSrc||img.src;if(!full)return;viewerImg.src=full;viewerImg.alt=img.alt||'Full-size image';viewerCaption.textContent=img.dataset.zoomCaption||img.alt||'FULL-SIZE IMAGE';const source=img.dataset.sourceUrl||'';viewerSource.hidden=!source;if(source)viewerSource.href=source;viewer.classList.remove('zoomed');viewer.classList.add('open');viewer.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';}
  function closeViewer(){viewer.classList.remove('open','zoomed');viewer.setAttribute('aria-hidden','true');viewerImg.src='';if(!document.querySelector('.species-modal.open,.photo-lightbox.open'))document.body.style.overflow='';}
  document.getElementById('universalImageClose').addEventListener('click',closeViewer);
  document.getElementById('universalImageStage').addEventListener('click',e=>{if(e.target===viewerImg)viewer.classList.toggle('zoomed');});
  viewer.addEventListener('click',e=>{if(e.target===viewer)closeViewer();});
  document.addEventListener('click',e=>{const img=e.target.closest('img');if(!img||viewer.contains(img)||img.classList.contains('no-zoom'))return;if(!img.src&&!img.currentSrc)return;e.preventDefault();e.stopImmediatePropagation();openViewer(img);},true);
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&viewer.classList.contains('open')){e.stopImmediatePropagation();closeViewer();}},true);

  /* ---------- Wikimedia Commons media QC ---------- */
  const mediaCache=new Map();
  const curated={
    'spinosaurus aegyptiacus':{evidence:'File:Digital skeletal reconstruction of Spinosaurus.png',life:'File:Spinosaurus aegyptiacus life reconstruction.png'},
    'tyrannosaurus rex':{evidence:'File:Tyrannosaurus rex skeleton (cast of specimen MOR 555) at Cleveland Museum of Natural History.jpg',life:'File:Life reconstruction of Tyrannosaurus rex specimen TMP 1981.006.0001 ("Black Beauty").png'},
    'velociraptor mongoliensis':{evidence:'File:Velociraptor skeleton.jpg',life:'File:Velociraptor Restoration.png'},
    'triceratops spp.':{evidence:'File:Skeleton of triceratops.jpg',life:'File:Triceratops horridus.png'},
    'triceratops':{evidence:'File:Skeleton of triceratops.jpg',life:'File:Triceratops horridus.png'},
    'allosaurus':{evidence:'File:Allosaurus - Napoli Paleontological Museum.png',life:'File:Allosaurus Life Reconstruction.jpg'},
    'albertosaurus':{life:'File:Albertosaurus sarcophagus.png'},
    'brachiosaurus altithorax':{evidence:'File:Brachiosaurus Composite Skeletal.svg',life:'File:202009 Brachiosaurus altithorax.png'}
  };
  function parseCommonsPage(page,curatedFlag=false){const ii=page?.imageinfo?.[0]||{},m=ii.extmetadata||{},cats=(page?.categories||[]).map(c=>String(c.title||'').replace(/^Category:/,'')).filter(Boolean);return{title:page?.title||'',display:ii.thumburl||ii.url||'',full:ii.url||ii.thumburl||'',source:ii.descriptionurl||'',width:ii.width||0,height:ii.height||0,artist:stripHtml(m.Artist?.value||m.Credit?.value||''),credit:stripHtml(m.Credit?.value||''),license:stripHtml(m.LicenseShortName?.value||m.UsageTerms?.value||''),licenseUrl:stripHtml(m.LicenseUrl?.value||''),description:stripHtml(m.ImageDescription?.value||''),categories:cats,curated:curatedFlag};}
  async function fetchCommonsFile(fileTitle){const key='file:'+fileTitle;if(mediaCache.has(key))return mediaCache.get(key);const promise=(async()=>{const p=new URLSearchParams({action:'query',format:'json',origin:'*',titles:fileTitle,prop:'imageinfo|categories',cllimit:'max',iiprop:'url|size|extmetadata',iiurlwidth:'1800'});const r=await fetch('https://commons.wikimedia.org/w/api.php?'+p);if(!r.ok)throw new Error('commons '+r.status);const j=await r.json(),page=Object.values(j.query?.pages||{})[0];const item=parseCommonsPage(page,true);return item.display?item:null;})().catch(()=>null);mediaCache.set(key,promise);return promise;}
  async function commonsSearch(query){const key='search:'+query;if(mediaCache.has(key))return mediaCache.get(key);const promise=(async()=>{const p=new URLSearchParams({action:'query',format:'json',origin:'*',generator:'search',gsrsearch:query,gsrnamespace:'6',gsrlimit:'24',prop:'imageinfo|categories',cllimit:'max',iiprop:'url|size|extmetadata',iiurlwidth:'1600'});const r=await fetch('https://commons.wikimedia.org/w/api.php?'+p);if(!r.ok)throw new Error('commons '+r.status);const j=await r.json();return Object.values(j.query?.pages||{}).map(page=>parseCommonsPage(page,false)).filter(x=>x.display&&x.full);})().catch(()=>[]);mediaCache.set(key,promise);return promise;}

  const hardReject=['inaccurate dinosaur restorations','obsolete paleontological views','historical image','annual report','bulletin','newsletter','journal','book cover','cover page','title page','report cover','newspaper','stamp','postage','coin','toy','plush','lego','logo','icon','meme','screenshot','colored pencil','colour pencil','pencil drawing','sketch','cartoon','doodle','tattoo'];
  const evidenceReject=['life restoration','life reconstruction','paleoart','artist impression','model','statue','animatronic','sculpture','diagram','cladogram','phylogeny','airway','cross-section','ct scan','size comparison','comparison chart','range map','map'];
  const lifeReject=['skeleton','skeletal','fossil','skull','specimen','bones','museum mount','mounted skeleton','cast','diagram','cladogram','phylogeny','size comparison','comparison chart','range map','map','model','statue','animatronic','sculpture'];
  function textBlob(c){return(c.title+' '+c.description+' '+(c.categories||[]).join(' ')).toLowerCase();}
  function scoreCandidate(c,mode,taxon){const t=textBlob(c),g=genus(taxon),title=String(c.title||'').toLowerCase();if(hardReject.some(w=>t.includes(w)))return-1000;if((c.categories||[]).some(x=>/inaccurate dinosaur restorations|historical dinosaur restorations|obsolete/i.test(x)))return-1000;if(mode==='evidence'&&evidenceReject.some(w=>t.includes(w)))return-150;if(mode==='life'&&lifeReject.some(w=>t.includes(w)))return-150;let score=0;const minDim=Math.min(c.width||0,c.height||0),maxDim=Math.max(c.width||0,c.height||0);score+=Math.min(maxDim/1200,3);if(minDim>=500)score+=1;if(maxDim>=2000)score+=1;if(g&&title.includes(g))score+=7;else if(g&&t.includes(g))score+=2;else score-=5;if(mode==='evidence'){['mounted skeleton','skeleton','skeletal','fossil','specimen','holotype','skull','museum','bones','cast'].forEach(w=>{if(t.includes(w))score+=w==='museum'?1.2:2.5;});['quality image','featured picture'].forEach(w=>{if(t.includes(w))score+=2;});}else{['life reconstruction','life restoration','restoration','reconstruction','paleoart','artistic restoration'].forEach(w=>{if(t.includes(w))score+=3;});if(/202[2-9]/.test(t))score+=1.5;if(/201[8-9]|202[0-1]/.test(t))score+=.6;}if(c.license)score+=1;if(c.artist&&c.artist.length>2)score+=.6;return score;}
  async function findCommonsMedia(name,mode){const key=mode+':'+name;if(mediaCache.has(key))return mediaCache.get(key);const promise=(async()=>{const cur=curated[String(name).toLowerCase()]?.[mode]||curated[normalizedTaxon(name).toLowerCase()]?.[mode];if(cur){const exact=await fetchCommonsFile(cur);if(exact)return exact;}const clean=normalizedTaxon(name),qs=mode==='evidence'?[`intitle:${genus(clean)} ${clean} mounted skeleton`,`intitle:${genus(clean)} ${clean} skeleton museum`,`intitle:${genus(clean)} ${clean} fossil specimen`,`intitle:${genus(clean)} ${clean} skull`]:[`intitle:${genus(clean)} ${clean} life reconstruction`,`intitle:${genus(clean)} ${clean} life restoration`,`intitle:${genus(clean)} ${clean} paleoart`];let best=null,bestScore=-999;for(const q of qs){const rows=await commonsSearch(q);for(const c of rows){const s=scoreCandidate(c,mode,clean);if(s>bestScore){best=c;bestScore=s;}}if(bestScore>=12)break;}return bestScore>=5?best:null;})();mediaCache.set(key,promise);return promise;}

  /* ---------- Dino-Dex dossier media switcher ---------- */
  function findSpeciesFromDossier(root){const h=root.querySelector('.dex-dossier-heading h2');if(!h)return null;const title=h.textContent.trim().toLowerCase();return dataset.find(s=>scientific(s).toLowerCase()===title||String(s.name).toLowerCase()===title)||null;}
  function mediaCreditHtml(media,label){if(!media)return`<strong>${label}</strong> // NO IMAGE PASSED QUALITY CONTROL. LEAVE BLANK UNTIL A BETTER FREE IMAGE IS FOUND.`;const who=media.artist||media.credit||'Wikimedia Commons contributor',lic=media.license||'Free media on Wikimedia Commons',badge=media.curated?' <span class="license">• CURATED SELECTION</span>':'';return`<strong>${label}</strong> // ${esc(who)} <span class="license">• ${esc(lic)}</span>${badge} // <a href="${esc(media.source)}" target="_blank" rel="noopener">SOURCE & LICENSE ↗</a><span class="dex-media-hint">CLICK IMAGE FOR FULL SIZE</span>`;}
  function enhanceDossier(root){if(!root||root.dataset.mediaEnhanced==='1')return;const species=findSpeciesFromDossier(root);if(!species)return;const wrap=root.querySelector('.dex-dossier-image-wrap');if(!wrap)return;root.dataset.mediaEnhanced='1';root.classList.add('dex-media-enhanced');const tabs=document.createElement('div');tabs.className='dex-media-tabs';tabs.innerHTML='<button class="dex-media-tab active" data-media-mode="evidence" type="button" disabled>FOSSIL / SKELETAL EVIDENCE</button><button class="dex-media-tab" data-media-mode="life" type="button" disabled>LIFE RECONSTRUCTION</button>';const stage=document.createElement('div');stage.className='dex-media-stage';stage.innerHTML=`<div class="dex-media-placeholder">${esc((species.name.match(/[A-Za-z]+/g)||['?']).slice(0,2).map(x=>x[0]).join('').toUpperCase())}</div><div class="dex-media-state">QUALITY-CHECKING FREE MEDIA...</div><img class="dex-media-image" alt="${esc(scientific(species))}">`;const credit=document.createElement('div');credit.className='dex-media-credit';credit.textContent='SEARCHING CURATED AND QUALITY-FILTERED WIKIMEDIA COMMONS MEDIA...';wrap.append(tabs,stage,credit);const display=stage.querySelector('.dex-media-image'),status=stage.querySelector('.dex-media-state'),buttons=[...tabs.querySelectorAll('.dex-media-tab')];const media={evidence:null,life:null};function show(which){const m=media[which];if(!m)return;buttons.forEach(b=>b.classList.toggle('active',b.dataset.mediaMode===which));display.src=m.display;display.dataset.fullSrc=m.full;display.dataset.sourceUrl=m.source;display.dataset.zoomCaption=`${scientific(species)} // ${which==='evidence'?'fossil or skeletal reference':'life reconstruction'}`;display.alt=`${scientific(species)} ${which==='evidence'?'fossil or skeletal reference':'life reconstruction'}`;credit.innerHTML=mediaCreditHtml(m,which==='evidence'?'FOSSIL / SKELETAL EVIDENCE':'LIFE RECONSTRUCTION');status.textContent=(m.curated?'CURATED ':'')+(which==='evidence'?'EVIDENCE VIEW':'RECONSTRUCTION VIEW');}buttons.forEach(b=>b.addEventListener('click',()=>show(b.dataset.mediaMode)));Promise.all([findCommonsMedia(scientific(species),'evidence'),findCommonsMedia(scientific(species),'life')]).then(([evidence,life])=>{media.evidence=evidence;media.life=life;buttons[0].disabled=!evidence;buttons[1].disabled=!life;buttons[0].title=evidence?'Evidence image passed media quality control':'No evidence image passed media quality control';buttons[1].title=life?'Life reconstruction passed media quality control':'No life reconstruction passed media quality control';status.textContent=(evidence||life)?'MEDIA QC COMPLETE':'NO MEDIA PASSED QC';if(evidence)show('evidence');else if(life)show('life');else credit.innerHTML=mediaCreditHtml(null,'MEDIA');});}
  const modalContent=document.getElementById('speciesModalContent');if(modalContent){const observer=new MutationObserver(()=>{const root=modalContent.querySelector('.dex-dossier-upgraded');if(root)enhanceDossier(root);});observer.observe(modalContent,{childList:true,subtree:true});const existing=modalContent.querySelector('.dex-dossier-upgraded');if(existing)enhanceDossier(existing);}
})();